[package]
name = "cp_hierarchical_clustering"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "*"
rayon = "*"
rand = "*"
polars = "*"
serde = "*"
num_cpus = "*"

[profile.test]
inherits = "release"
